### PR TITLE
(maint) mark project unmaintained

### PR DESCRIPTION
**Pull request by wkalt**

### CODE REVIEW

**Comment by wkalt** [comment]
ping @nathanielksmith @rlinehan just a conversation starter

**Comment by dhgwilliam** [comment]
i'd be willing to consider taking this over if @voxpupuli isn't interested

**Comment by rlinehan** [comment]
This makes me really sad, because I'd love to have the time and energy to maintain this, but I think it's unfortunately true. @dhgwilliam if you or @voxpupuli would be interested in taking this over that would be awesome!

**Comment by rlinehan** [comment]
Closing this as ownership and maintenance has been transferred to Vox Pupuli.

**Pull request closed without merging**
